### ISSUE TITLE
SQL error on artisan migrate:fresh

### ISSUE THREAD

**Issue by peyman-mohamadpour** [ThisPR/Store#1]
**Steps to reproduce:**

1. `git pull`
2. `composer install`
3. `yarn install`
4. `yarn run dev`
5. `php artisan migrate:fresh` and made the choice `yes` at:
    > Do you really wish to run this command? (yes/no)

    prompt. The error comes:

    >    Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

I think you should document the connection setting as well in your `README.md` file.

**Comment by Rasoul678** [comment]
Maybe, You don't have a user named 'forge'. In my opinion there is something wrong with your .env file.

**Comment by peyman-mohamadpour** [comment]
> Maybe, You don't have a user named 'forge'. In my opinion there is something wrong with your .env file.

Thanks for your reply. There is no `.env` file in your documented instructions (`README.md`). Please update it accordingly. Documentation is an important part of an application. Reinstall your application from scratch and try to emulate a new user behavior and populate a comprehensive documentation.

**Comment by babak271** [comment]
Many thanks to you for your comment.
Required instructions were added to README.md
