### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by peyman-mohamadpour** [ThisPR/Store#2]
**Steps to reproduce:**

1. I created a virtual host named `store.local`, and pointed to `{DOCUMENT_ROOT}/Store/public` (Should be documented as well)
2. I alse created a MySQL database and provided the database connection settings into: `./config/database.php` under `connections` > `mysql` key, I still have problems with application.
3. I browsed into `http://store.local/admin` and:

    > 500 | Server Error
4. Browser console gives me:

    > Status Code: 500 Internal Server Error

![ChromeConsole](https://user-images.githubusercontent.com/61138819/77670261-93e78f00-6fa3-11ea-83b9-63b975b98de7.jpg)

**Comment by babak271** [comment]
> **Steps to reproduce:**
> 
> 1. I created a virtual host named `store.local`, and pointed to `{DOCUMENT_ROOT}/Store/public` (Should be documented as well)
> 2. I alse created a MySQL database and provided the database connection settings into: `./config/database.php` under `connections` > `mysql` key, I still have problems with application.
> 3. I browsed into `http://store.local/admin` and:
>    > 500 | Server Error
> 4. Browser console gives me:
>    > Status Code: 500 Internal Server Error
> 
> ![ChromeConsole](https://user-images.githubusercontent.com/61138819/77670261-93e78f00-6fa3-11ea-83b9-63b975b98de7.jpg)

You should rename the .env.example file and then add your database config into it. config/database must be remain intact. We will add these steps in the Readme.
