### ISSUE TITLE
Admin session lost after browsing to front

### ISSUE THREAD

**Issue by peyman-mohamadpour** [ThisPR/Store#3]
Admin session is not persisted during browsing into the front.

**Stepst to reproduce:**

1. Go to admin section and login, using admin credentials.
2. Go to front, and your session is lost. You should login or signup

**Comment by babak271** [comment]
Could you explain more about this deficiency?
A test was run as following:
1. Login as an admin.
2. Open a new tab on front page (/) and login as a customer.
3. Now we have two tabs with 2 logged in users. (We doubt that is it wrong or not)
4. When you press logout, you'll log out from both customer and admin pages.

**Comment by Rasoul678** [comment]
I've fixed this so-called anomaly. So now:
1- You can log in as either admin or customer
2- In both back and front section, you can log out from admin account.
3- If you back and forth in sections you won't lose your session hopefully!
4- We can see our admin name in front page which is linked to admin dashboard in back.
