### ISSUE TITLE
Checkout and cart management process is misleading

### ISSUE THREAD

**Issue by peyman-mohamadpour** [ThisPR/Store#4]
Steps to reproduce:

1. Go to the front logged in with your username & password
2. Add some products into your cart
3. go to Checkout page
4. Go back to your cart. Nothing is inside. Your cart is empty and the trace is gone forever. You should start over!

**Comment by babak271** [comment]
### Steps for buying products
Following steps are assumed:
1. Add your favorite products to cart
2. Press checkout button on shopping cart page to make a order in the site
3. View your orders in the profile page, by clicking on your full name on navbar

@peyman-mohamadpour , I haven't catch your mean. There isn't any checkout page.

**Comment by peyman-mohamadpour** [comment]
Another misleading process is for visitors.

Visitors (and not logged in users) may browse the store and add items into the card, using **add to cart** button. But there is no cart to see added items.

**Comment by babak271** [comment]
Commit 1028edd7ee16e6761ef64dbb9f57f719d4c8a30f resolves this isssue by adding cart to session for guest users and transferring them to shopping cart after signing up or logging in.
