### ISSUE TITLE
Entity CRUD process is misleading

### ISSUE THREAD

**Issue by peyman-mohamadpour** [ThisPR/Store#5]
Steps to reproduce:

1. Go to admin panel at using the admin credentials
2. You see some number of products, categories and orders. 500, 7, 300 accordingly in my case.
3. Choose one (products in my case) and soft delete or hard delete some of items. You face this message:
> XXXXXX has been deleted successfully.

or
> XXXXXX has been deleted permanently.

Go back to admin panel dashboard, and still you will see the exact same number of items (500 products in my case).

Also, where are does soft deleted products? How can I access them?

Choose the order option (300 items inmy case). There is nothing inside!

If I register a new user in front and go some shopping, and come back as admin into dashboard and go to orders, it still counts a huge number (300 in my case), but I can just see one new order, by the new user.

I think your application suffers from plenty of rational assumptions.

Try to find and remove all those misleading assumptions.

**Comment by Rasoul678** [comment]
I think our application is suffering from simplicity and lack of functionality and not "rational" assumptions. We thought about details and different parts in application. But you are right, we have to fix these problems:
First, We should not hard code the counter in dashboard page. I will add functionality to this section right away.
Second, Order comes after checkout. I mean a customer must check out an order then we would have order in admin panel. So we had two options for now, we could hard code or seed fake order to table. Of course at the end of the day we will have fully functional and practical order page for admin panel.

**Comment by Rasoul678** [comment]
I've fixed hard coding numbers in dashboard. now if you add or delete in back area. you will see real numbers accordingly.
