### ISSUE TITLE
Improve faker data process (seed process)

### ISSUE THREAD

**Issue by peyman-mohamadpour** [ThisPR/Store#8]
# Make it recognizable

Every time I refresh product list (homepage) I see new images and all the same new image as assigned to all products. This way I can not differentiate between defferent products.

Change this behaviour and assign a single different and persistent image into every single fake product, so that one can regnize what have added to the cart.

# Make it persistent between future updates

As far as I know, after each codebase update, you are forcing the user to remove whole database information and reseed the database with all new information.

Please change this behaviour and let the user keep its old data and only update the database schema.

**Comment by babak271** [comment]
spatie/imageLibrary was added. d0c6fda7064d2f6328d933c8d659f493c0a2bd36
